"""add_sim_type_table

Revision ID: 883f24a6ae89
Revises: cbbf50c0b41e
Create Date: 2025-12-05 18:28:40.280434
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883f24a6ae89'
down_revision = 'cbbf50c0b41e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_type_name'), 'sim_type', ['name'], unique=True)
    op.add_column('sim', sa.Column('sim_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sim', 'sim_type', ['sim_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sim', type_='foreignkey')
    op.drop_column('sim', 'sim_type_id')
    op.drop_index(op.f('ix_sim_type_name'), table_name='sim_type')
    op.drop_table('sim_type')
    # ### end Alembic commands ###
