"""add_oib_to_customer

Revision ID: 95d70c52a612
Revises: a9af06d71416
Create Date: 2025-12-05 19:30:59.536957
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d70c52a612'
down_revision = 'a9af06d71416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('oib', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_customer_oib'), 'customer', ['oib'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_oib'), table_name='customer')
    op.drop_column('customer', 'oib')
    # ### end Alembic commands ###
