"""initial schema

Revision ID: cbbf50c0b41e
Revises: 
Create Date: 2025-11-17 19:32:38.816566
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbf50c0b41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('sim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iccid', sa.String(length=32), nullable=False),
    sa.Column('msisdn', sa.String(length=16), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_iccid'), 'sim', ['iccid'], unique=True)
    op.create_index(op.f('ix_sim_msisdn'), 'sim', ['msisdn'], unique=True)
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['sim_id'], ['sim.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'sim_id', name='uq_customer_sim')
    )
    op.create_index(op.f('ix_assignment_customer_id'), 'assignment', ['customer_id'], unique=False)
    op.create_index(op.f('ix_assignment_sim_id'), 'assignment', ['sim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_sim_id'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_customer_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_sim_msisdn'), table_name='sim')
    op.drop_index(op.f('ix_sim_iccid'), table_name='sim')
    op.drop_table('sim')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
